config/routes.rb
Rails.application.routes.draw do
  #get 'users/show'

  #get 'posts/new'

  #get 'users/top'
  root 'users#top'
  get 'top', to:'users#top', as: :top
  get '/profile/edit', to: 'users#edit', as: 'profile_edit'
  get '/profile/:id', to: 'users#show', as: 'profile'
  get '/follower_list/:id', to: 'users#follower_list', as: 'follower_list'
  get '/follow_list/:id', to: 'users#follow_list', as: 'follow_list'
  get '/sign_up', to: 'users#sign_up', as: 'sign_up'
  get '/sign_in', to: 'users#sign_in', as: 'sign_in'
  get '/sign_out', to: 'users#sign_out', as: 'sign_out'
  get '/follow/:id', to: 'users#follow', as: 'follow'
  
  #get 'posts/new', to:'posts#new', as: :new_post
  resources :posts do
    member do
      # いいね
      get 'like', to: 'posts#like', as: :like
    end
  end


  post '/sign_up', to: 'users#sign_up_process'
  post '/sign_in', to: 'users#sign_in_process'
  post '/profile/edit', to: 'users#update'
  post '/posts/:id/comment', to: 'posts#comment', as: 'comment_post'
  
  #delete '/posts/:id', to: 'posts#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # リレーション
  has_many :posts
  has_many :post_likes
  has_many :post_comments
  has_many :follows
  has_many :followers, foreign_key: :follow_user_id, class_name: "Follow"
  
    # バリデーション
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
  validates :name, presence: true
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: true
  validates :password, presence: true, length:{minimum: 6} 
    
  # データの初期保存前に、パスワードを暗号化するメソッド(convert_password)を
  #実行するよう設定
  #before_save :convert_password
  before_create :convert_password
 
  # パスワードを暗号化するメソッド
  def convert_password
    self.password = User.generate_password(self.password)
  end
 
  # パスワードをmd5に変換するメソッド
  def self.generate_password(password)
    # パスワードに適当な文字列を付加して暗号化する
    salt = "h!hgamcRAdh38bajhvgai17ysvb"
    Digest::MD5.hexdigest(salt + password)
  end
  
  # ユーザーがフォローされているかどうかを判定
  def followed_by?(user)
    user.follows.exists?(follow_user_id: self.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:sign_up, :sign_up_process, :sign_in, :sign_in_process]
  before_action :redirect_to_top_if_signed_in, only: [:sign_up, :sign_in]
  
  def top
    # トップページ
     if params[:word].present?
      # キーワード検索処理
      @posts = Post.where("caption like ?", "%#{params[:word]}%").order("id desc")
    else
      # 一覧表示処理
      @posts = Post.all.order("id desc").page(params[:page])
    end
    @recommends = User.where.not(id: current_user.id).where.not(id: current_user.follows.pluck(:follow_user_id)).limit(3)
  end
  
  def show
    # ユーザー情報取得
    @user = User.find(params[:id])
    
    # ユーザーの投稿データ取得
    @posts = Post.where(user_id: @user.id)
    
    @followers = User.where(id: Follow.where(follow_user_id: @user.id).pluck(:user_id))
  end
  
  # ユーザー登録ページ
  def sign_up
    @user = User.new
    render layout: "application_not_login"
  end
  
  # ユーザー登録処理
  def sign_up_process
    # ここに処理を実装
    user = User.new(user_params)
    if user.save
      # 登録が成功したらサインインしてトップページへ
      user_sign_in(user)
      redirect_to top_path and return
    else
      #DB登録失敗なのでエラーメッセージを表示する
      # 登録が失敗したらユーザー登録ページへ
      flash[:danger] = "ユーザー登録に失敗しました。"
      redirect_to('/sign_up')
    end
  end
  
  # サインインページ
  def sign_in
    @user = User.new
    render layout: "application_not_login"
  end
  
  # サインイン処理
  def sign_in_process
    # パスワードをmd5に変換
    password_md5 = User.generate_password(user_params[:password])
    # メールアドレスとパスワードをもとにデータベースからデータを取得
    user = User.find_by(email: user_params[:email], password: password_md5)
    if user
      # セッション処理
      user_sign_in(user)
      # トップ画面へ遷移する
      redirect_to top_path and return
    else
      #サインインに失敗した時にはエラーメッセージを出す
      flash[:danger] = "サインインに失敗しました。"
      redirect_to('/sign_in')
    end
  end
  
  # サインアウト
  def sign_out
    # ユーザーセッションを破棄
    user_sign_out
    # サインインページへ遷移
    redirect_to sign_in_path and return
  end
  
  # プロフィール編集ページ
  def edit
    @user = User.find(current_user.id)
  end
   
  # プロフィール更新処理
  def update
    #26-3プロフィール画像のアップロード処理
    upload_file = params[:user][:image]
    if upload_file.present?
      # あった場合はこの中の処理が実行される
      upload_file_name = upload_file.original_filename
      output_dir = Rails.root.join('public','users')
      output_path = output_dir + upload_file_name
      File.open(output_path, 'w+b') do |f|
        f.write(upload_file.read)
      end
      #データベースのプロフィール情報更新処理
      current_user.update(user_params.merge({image: upload_file.original_filename}))
    else
      #画像データがなかった場合はこちらの処理が実行される。
      #データベースのプロフィール情報更新処理
      current_user.update(user_params)
    end
    redirect_to profile_edit_path
    flash[:success] = "プロフィール更新したよぉ"
    return
  end
  
  # フォロー処理
  def follow
    @user = User.find(params[:id])
    if Follow.exists?(user_id: current_user.id, follow_user_id: @user.id)
      # フォローを解除
      Follow.find_by(user_id: current_user.id, follow_user_id: @user.id).destroy
    else
      # フォローする
      Follow.create(user_id: current_user.id, follow_user_id: @user.id)
    end
    @followers = User.where(id: Follow.where(follow_user_id: @user.id).pluck(:user_id))
    redirect_back(fallback_location: top_path, notice: "フォローを更新しました。")
  end
  
  # フォローリスト
  def follow_list
      # プロフィール情報の取得
      @user = User.find(params[:id])
      @users = User.where(id: Follow.where(user_id: @user.id).pluck(:follow_user_id))
      @followers = User.where(id: Follow.where(follow_user_id: @user.id).pluck(:user_id))
  end
  
  #フォロワーリスト
  def follower_list
    # プロフィール情報の取得
    @user = User.find(params[:id])
    @followers = User.where(id: Follow.where(follow_user_id: @user.id).pluck(:user_id))
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :comment)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # 渡されたユーザーでサインインする
  def user_sign_in(user)
    session[:user_id] = user.id
  end
    
   # 現在サインイン中のユーザー情報を返す
  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id])
    else
      @current_user
    end
  end
  
  # サインアウトする
  def user_sign_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  # ユーザーがサインインしていればtrue, そうでなければfalseを返す
  def user_signed_in?
    current_user.present?
  end
  
  # 認証チェック
  def authorize
    redirect_to sign_in_path unless user_signed_in?
  end
  
  # サインイン済みならトップページに遷移する
  def redirect_to_top_if_signed_in
    redirect_to top_path and return if user_signed_in?
  end
  
  # プロフィール画像がなかったらダミー画像を指定する
  def image_url(user)
    if user.image.blank?
      "https://dummyimage.com/200x200/000/fff"
    else
      "/users/#{user.image}"
    end
  end
end

app/views/users/_profile.html.erb
<!-- プロフィール部分 -->
<div class="profile">
    <div class="image">
      <div style="background: url('<%= image_url(@user) %>'); background-position: 50%; background-size: cover;"></div>
    </div>
    <div class="info">
      <div class="name">
        <h1>
          <!-- ユーザー名 -->
          <%= @user.name %>
        </h1>
        <div class="actions">
          <% if @user.id == current_user.id %>
          <div class="edit">
            <%= link_to "プロフィール編集", profile_edit_path %>
          </div>
          <% else %>
          <div class="follow">
            <%= link_to @user.followed_by?(current_user)? "フォロー解除": "フォローする", follow_path(@user.id) %>
          </div>
          <% end %>
        </div>
      </div>
      <div class="status">
        <p class="posts_count">投稿数 <%= @user.posts.length %>件</p>
        <p class="follower_count">
          <%= link_to "フォロワー#{@followers.length}人", follower_list_path(@user) %>
        </p>
        <p class="follow_count"><%= link_to "#{@user.follows.length}人をフォロー中", follow_list_path(@user) %>
      </div>
      <div class="comment">
        <%= @user.comment %>
      </div>
    </div>
</div>

app/views/users/edit.html.erb
<div class="profile_edit container">
  <%= form_for @user, url: profile_edit_path, method: :post do |f| %>
    <div class="field">
      <%= f.label :name, "名前" %>
      <%= f.text_field :name, placeholder: "名前を入力して下さい。" %>
    </div>
    <div class="field">
      <%= f.label :email, "メールアドレス" %>
      <%= f.text_field :email, placeholder: "メールアドレスを入力して下さい。" %>
    </div>
    <div class="field">
      <%= f.label :comment, "コメント" %>
      <%= f.text_field :comment, placeholder: "自己紹介など" %>
    </div>
    <div class="field">
      <label>プロフィール画像</label>
      <div class="file_wrap">
        <%= f.file_field :image %>
      </div>
    </div>
    <div class="button_wrap">
      <input type="submit" value="保存する" class="button">
    </div>
  <% end %>
</div>

app/views/users/follow_list.html.erb
<div class="user container">
  <!-- プロフィール部分 -->
  <%= render partial: 'users/profile' %>
  <!-- フォローリスト部分 -->
  <h1>フォロー</h1>
  <% if @users.any? %>
  <ul class="users">
    <% @users.each do |user| %>
    <li>
      <div style="background: url('<%= image_url(user) %>'); background-position: 50%; background-size: cover;" class="image"></div>
      <%= link_to profile_path(user) do %>
        <span class="name"><%= user.name %></span>
      <% end %>
      <% if user.id != current_user.id %>
      <%= link_to user.followed_by?(current_user)? "フォロー解除": "フォローする", follow_path(user.id), class: "button" %>
      <% end %>
    </li>
    <% end %>
  </ul>
  <% else %>
    <p class="empty">ユーザーが存在しません。</p>
  <% end %>
</div>

app/views/users/follower_list.html.erb
<div class="user container">
  <!-- プロフィール部分 -->
  <%= render partial: 'users/profile' %>
  <!-- フォロワーリスト部分 -->
  <h1>フォロワー</h1>
  <% if @followers.any? %>
  <ul class="users">
    <% @followers.each do |follower| %>
    <li>
      <div style="background: url('<%= image_url(follower) %>'); background-position: 50%; background-size: cover;" class="image"></div>
      <%= link_to profile_path(follower) do %>
        <span class="name"><%= follower.name %></span>
      <% end %>
      <% if follower.id != current_user.id %>
      <%= link_to follower.followed_by?(current_user)? "フォロー解除": "フォローする", follow_path(follower.id), class: "button" %>
      <% end %>
    </li>
    <% end %>
  </ul>
  <% else %>
    <p class="empty">ユーザーが存在しません。</p>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user container">
  <!-- プロフィール部分 -->
  <%= render partial: 'users/profile' %>
  <!-- 投稿画像部分 -->
  <div class="posts">
    <ul>
      <% @posts.each do |post| %>
      <% post.post_images.each do |post_image| %>
      <li>
        <div style="background: url('<%= "/images/#{post_image.name}" %>'); background-repeat: no-repeat; background-position: 50%;"></div>
      </li>
      <% end %>
    <% end %>
    </ul>
  </div>
</div>

app/views/users/sign_in.html.erb
<div class="sign_in">
  <div class="contents">
    <div class="sign_in_form">
      <h1>Photo</h1>
      <%= form_for @user, url: sign_in_path do |f| %>
        <div class="field">
          <%= f.email_field :email, placeholder: "メールアドレス" %>
        </div>
        <div class="field">
          <%= f.password_field :password, placeholder: "パスワード" %>
        </div>
        <button>サインインする</button>
      <% end %>
    </div>
    <div class="sign_in_link">
      <p>アカウントをお持ちですか？ <%= link_to '新規登録する', '/sign_up' %></p>
    </div>
  </div>
</div>

app/views/users/sign_up.html.erb
<div class="sign_up">
  <div class="contents">
    <div class="sign_up_form">
      <h1>Photo</h1>
      <p>友達のphotoをチェックしよう</p>
      <%= form_for @user, url: sign_up_path do |f| %>
        <div class="field">
          <%= f.text_field :name, placeholder: "ユーザーネーム" %>
        </div>
        <div class="field">
          <%= f.email_field :email, placeholder: "メールアドレス" %>
        </div>
        <div class="field">
          <%= f.password_field :password, placeholder: "パスワード" %>
        </div>
        <button>登録する</button>
      <% end %>
    </div>
    <div class="sign_in_link">
      <p>アカウントをお持ちですか？ <%= link_to 'サインインする', '/sign_in' %></p>
    </div>
  </div>
</div>

app/views/users/top.html.erb
<div class="top container">
  <% if @posts.any? %>
  <ul class="posts">
    <div><%= page_entries_info @posts %></div>
    <% @posts.each do |post| %>
    <li>
      <!-- 投稿者のアイコン -->
      <div class="user">
        <div style="background: url('<%= image_url(post.user) %>'); background-position: center; background-size: cover" class="image"></div>
        <p><%= link_to post.user.name, profile_path(post.user) %></p>
      </div>
      <!-- 投稿画像 -->
      <% post.post_images.each do |post_image| %>
      <div class="image_wrap">
        <%= image_tag "/images/#{post_image.name}" %>
      </div>
      <% end %>
      <!-- テキスト部分 -->
      <div class="info">
        <div class="action">
          <%= link_to like_post_path(post) do %>
            <i class="fa <%= post.like_from?(current_user)? "fa-heart active" : "fa-heart-o" %>"></i>
          <% end %>
          <label for="post-comment-">
            <i class="fa fa-comment-o"></i>
          </label>
          <% if post.user_id == current_user.id %>
            <%= link_to post_path(post), method: :delete do %>
              <i class="fa fa-close"></i>
            <% end %>
          <% end %>
        </div>
        <div class="like">
          <p>いいね <%= post.post_likes.length %>件</p>
        </div>
        <!-- コメント部分 -->
        <div class="comment">
          <ul>
            <!-- 投稿者のキャプション -->
            <% if post.caption.present? %>
            <li>
              <span class="user_name"><%= post.user.name %></span>
              <span class="caption"><%= post.caption %></span>
            </li>
            <% end %>
            <!-- 画像へのコメント -->
            <% post.post_comments.each do |post_comment| %>
            <li>
              <span class="user_name"><%= post_comment.user.name %></span>
              <span class="caption"><%= post_comment.comment %></span>
            </li>
            <% end %>
          </ul>
          <!-- コメント入力部分 -->
          <div class="text_wrap">
            <%= form_for post.post_comments.new, url: comment_post_path(post) do |f| %>
              <div class="field">
                <%= f.text_field :comment, id: "post-comment-#{post.id}", placeholder: "コメントを入力" %>
                <%= f.submit "送信" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </li>
    <% end %>
    <div><%= paginate @posts %></div>
  </ul>
  <% else %>
  <p class="empty">投稿がありません。</p>
  <% end %>
  <!-- おすすめユーザー -->
  <% if @recommends.any? %>
  <div class="recommend">
    <h2>おすすめ</h2>
    <ul>
      <% @recommends.each do |user| %>
      <li>
        <%= link_to profile_path(user) do %>
          <img src="<%= image_url(user) %>">
          <p><%= user.name %></p>
        <% end %>
        <%= link_to "フォローする", follow_path(user), class: "button" %>
      </li>
      <% end %>
    </ul>
  </div>
  <% end %>
</div>