config/routes.rb
Rails.application.routes.draw do
  #get 'users/show'

  #get 'posts/new'

  #get 'users/top'
  root 'users#top'
  get 'top', to:'users#top', as: :top
  get '/profile/edit', to: 'users#edit', as: 'profile_edit'
  get '/profile/:id', to: 'users#show', as: 'profile'
  get '/follower_list/:id', to: 'users#follower_list', as: 'follower_list'
  get '/follow_list/:id', to: 'users#follow_list', as: 'follow_list'
  get '/sign_up', to: 'users#sign_up', as: 'sign_up'
  get '/sign_in', to: 'users#sign_in', as: 'sign_in'
  get '/sign_out', to: 'users#sign_out', as: 'sign_out'
  get '/follow/:id', to: 'users#follow', as: 'follow'
  
  #get 'posts/new', to:'posts#new', as: :new_post
  resources :posts do
    member do
      # いいね
      get 'like', to: 'posts#like', as: :like
    end
  end


  post '/sign_up', to: 'users#sign_up_process'
  post '/sign_in', to: 'users#sign_in_process'
  post '/profile/edit', to: 'users#update'
  post '/posts/:id/comment', to: 'posts#comment', as: 'comment_post'
  
  #delete '/posts/:id', to: 'posts#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  </head>
  <body class="logined">
    <header class="global_header">
      <!-- ロゴ -->
      <div class="icon">
        <%= link_to top_path do %>
          <i class="fa fa-camera"></i>
        <% end %>
      </div>
      <%= link_to top_path do %>
        <h1 class="logo">Photo</h1>
      <% end %>
      <!-- 検索フォーム -->
      <form class="search">
        <input type="text" placeholder="検索ワードを入力" name="word" value="">
      </form>
      <!-- メニュー -->
      <ul class="menu">
        <li>
          <!-- サインアウト -->
          <a href="#">
            <%= link_to sign_out_path do %>
              <i class="fa fa-sign-out"></i>
            <% end %>
          </a>
        </li>
        <li>
          <!-- プロフィールページ -->
          <a href="#">
            <%= link_to profile_path(current_user) do %>  
              <i class="fa fa-user-o"></i>
            <% end %>
          </a>
        </li>
        <li>
          <!-- 投稿 -->
          <a href="#">
            <%= link_to new_post_path do %>
              <i class="fa fa-upload"></i>
            <% end %>
          </a>
        </li>
      </ul>
    </header>
    <% flash.each do |type, message| %>
    <div class="alert alert-<%= type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
        window.setTimeout(function() {
            $(".alert").slideUp();
        }, 3000);
    </script>
  </body>
</html>

app/views/layouts/application_not_login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
      window.setTimeout(function() {
        $(".alert").slideUp();
      }, 3000);
    </script>
  </body>
</html>